#### General Configuration Parameters for Data Collection####
TOWN: "Town01"

POSITIONS:  [[19, 66], [79, 14], [19, 57], [39, 53], [60, 26],
             [53, 76], [42, 13], [31, 71], [59, 35], [47, 16],
             [10, 61], [66, 3], [20, 79], [14, 56], [26, 69],
             [79, 19], [2, 29], [16, 14], [5, 57], [77, 68],
             [70, 73], [46, 67], [57, 50], [61, 49], [21, 12]
             ]
             
WEATHERS: ["ClearNoon", "WetNoon", "HardRainyNoon", "ClearSunset"]
NumberOfVehicles: [20, 45]  # The range for the random numbers that are going to be generated
NumberOfPedestrians: [35, 80] #[